id: I3F2DDF11
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:31:02+00:00'
last_modified: '2022-06-07T17:07:05.073672+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1054
  title: མཆོད་སྦྱིན་གཏོར་མའི་རྣམ་བཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FFA5:
      image_group_id: I1CZ1417
      title: ''
      total_pages: 30
      order: 1
      base_file: FFA5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
